# Generated by Django 2.0.7 on 2018-07-31 08:00

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20180731_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artical',
            options={'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': '分類'},
        ),
        migrations.AlterField(
            model_name='artical',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quickstart.NewsCategory', verbose_name='新聞分類'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploadImg'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='title',
            field=models.CharField(max_length=50, verbose_name='標題'),
        ),
    ]
