# Generated by Django 2.0.7 on 2018-08-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20180731_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '用戶',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('bbs_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.Artical')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.Users')),
            ],
            options={
                'verbose_name_plural': '點贊',
            },
        ),
    ]
