# Generated by Django 2.0.7 on 2018-08-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_users_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=500)),
                ('bbs_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.Artical')),
            ],
            options={
                'verbose_name_plural': '評論',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.Users'),
        ),
    ]
