# Generated by Django 2.0.7 on 2018-08-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20180801_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bbs_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='money',
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
