# Generated by Django 2.0.7 on 2018-08-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_auto_20180801_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='comment',
        ),
    ]
