# Generated by Django 2.0.7 on 2018-08-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_vote_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='status',
            new_name='isVote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='bbs_id',
        ),
    ]
